# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chessboard.ui'
#
# Created: Sun Mar  6 22:48:13 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(660, 800)
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 641, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.player_one_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.player_one_label.setObjectName("player_one_label")
        self.horizontalLayout.addWidget(self.player_one_label)
        self.player_one_edit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.player_one_edit.setObjectName("player_one_edit")
        self.horizontalLayout.addWidget(self.player_one_edit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.player_two_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.player_two_label.setObjectName("player_two_label")
        self.horizontalLayout.addWidget(self.player_two_label)
        self.player_two_edit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.player_two_edit.setObjectName("player_two_edit")
        self.horizontalLayout.addWidget(self.player_two_edit)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 700, 641, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.submit_btn = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.submit_btn.setObjectName("submit_btn")
        self.horizontalLayout_2.addWidget(self.submit_btn)
        self.chess_board = QtGui.QTableWidget(Form)
        self.chess_board.setGeometry(QtCore.QRect(10, 50, 640, 640))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chess_board.sizePolicy().hasHeightForWidth())
        self.chess_board.setSizePolicy(sizePolicy)
        self.chess_board.setAutoFillBackground(False)
        self.chess_board.setLineWidth(1)
        self.chess_board.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.chess_board.setTabKeyNavigation(False)
        self.chess_board.setProperty("showDropIndicator", False)
        self.chess_board.setDragDropOverwriteMode(False)
        self.chess_board.setAlternatingRowColors(False)
        self.chess_board.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.chess_board.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.chess_board.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.chess_board.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.chess_board.setGridStyle(QtCore.Qt.NoPen)
        self.chess_board.setCornerButtonEnabled(True)
        self.chess_board.setObjectName("chess_board")
        self.chess_board.setColumnCount(8)
        self.chess_board.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.chess_board.setHorizontalHeaderItem(7, item)
        self.chess_board.horizontalHeader().setVisible(False)
        self.chess_board.horizontalHeader().setStretchLastSection(False)
        self.chess_board.verticalHeader().setVisible(True)
        self.chess_board.verticalHeader().setDefaultSectionSize(30)
        self.chess_board.verticalHeader().setHighlightSections(False)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.player_one_label.setText(QtGui.QApplication.translate("Form", "Player 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.player_two_label.setText(QtGui.QApplication.translate("Form", "Player 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.submit_btn.setText(QtGui.QApplication.translate("Form", "Submit Move", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.verticalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.verticalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.verticalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.verticalHeaderItem(7).setText(QtGui.QApplication.translate("Form", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.chess_board.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Form", "New Column", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
